name: Xray Download and Upload

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  download_and_upload:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Xray
        run: |
          URL="https://github.com/XTLS/Xray-core/releases/download/v1.8.3/Xray-windows-64.zip"
          curl -sL -o Xray-windows-64.zip $URL
          unzip Xray-windows-64.zip xray.exe
          rm Xray-windows-64.zip

      - name: Upload xray.exe
        uses: actions/upload-artifact@v2
        with:
          name: xray-executable
          path: ./xray.exe
